package com.livechain.mybatis.model;

public class OrgCodesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_orgcodes.orgcode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String orgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_orgcodes.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_orgcodes.orgcode
     *
     * @return the value of empi_orgcodes.orgcode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_orgcodes.orgcode
     *
     * @param orgcode the value for empi_orgcodes.orgcode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_orgcodes.PID
     *
     * @return the value of empi_orgcodes.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_orgcodes.PID
     *
     * @param pid the value for empi_orgcodes.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setPid(String pid) {
        this.pid = pid;
    }
}