package com.livechain.mybatis.dao;


import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.livechain.mybatis.model.SimilarityExample;
import com.livechain.mybatis.model.SimilarityKey;
@MyBatisRepository
public interface SimilarityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_similarity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int countByExample(SimilarityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_similarity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int deleteByExample(SimilarityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_similarity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int deleteByPrimaryKey(SimilarityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_similarity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int insert(SimilarityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_similarity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int insertSelective(SimilarityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_similarity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    List<SimilarityKey> selectByExample(SimilarityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_similarity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByExampleSelective(@Param("record") SimilarityKey record, @Param("example") SimilarityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_similarity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByExample(@Param("record") SimilarityKey record, @Param("example") SimilarityExample example);
}