package com.livechain.mybatis.model;

import java.util.Date;

public class Credentials {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_credentials.crdid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private Integer crdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_credentials.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_credentials.type
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_credentials.num
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_credentials.regtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_credentials.endtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_credentials.status
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_credentials.crdid
     *
     * @return the value of empi_credentials.crdid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public Integer getCrdid() {
        return crdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_credentials.crdid
     *
     * @param crdid the value for empi_credentials.crdid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setCrdid(Integer crdid) {
        this.crdid = crdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_credentials.PID
     *
     * @return the value of empi_credentials.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_credentials.PID
     *
     * @param pid the value for empi_credentials.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_credentials.type
     *
     * @return the value of empi_credentials.type
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_credentials.type
     *
     * @param type the value for empi_credentials.type
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_credentials.num
     *
     * @return the value of empi_credentials.num
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_credentials.num
     *
     * @param num the value for empi_credentials.num
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_credentials.regtime
     *
     * @return the value of empi_credentials.regtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_credentials.regtime
     *
     * @param regtime the value for empi_credentials.regtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_credentials.endtime
     *
     * @return the value of empi_credentials.endtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_credentials.endtime
     *
     * @param endtime the value for empi_credentials.endtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_credentials.status
     *
     * @return the value of empi_credentials.status
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_credentials.status
     *
     * @param status the value for empi_credentials.status
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setStatus(String status) {
        this.status = status;
    }
}