package com.livechain.mybatis.model;

import java.util.Date;

public class OrgCodes extends OrgCodesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_orgcodes.uploadtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private Date uploadtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_orgcodes.uploadtime
     *
     * @return the value of empi_orgcodes.uploadtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public Date getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_orgcodes.uploadtime
     *
     * @param uploadtime the value for empi_orgcodes.uploadtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setUploadtime(Date uploadtime) {
        this.uploadtime = uploadtime;
    }
}