package com.livechain.mybatis.model;

public class PersonInDataWithBLOBs extends PersonInData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personindata.inparam
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	private String inparam;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personindata.outparam
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	private String outparam;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personindata.inparam
	 * @return  the value of personindata.inparam
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public String getInparam() {
		return inparam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personindata.inparam
	 * @param inparam  the value for personindata.inparam
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void setInparam(String inparam) {
		this.inparam = inparam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personindata.outparam
	 * @return  the value of personindata.outparam
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public String getOutparam() {
		return outparam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personindata.outparam
	 * @param outparam  the value for personindata.outparam
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void setOutparam(String outparam) {
		this.outparam = outparam;
	}
}