package com.livechain.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PersonExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public PersonExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andParentIsNull() {
            addCriterion("parent is null");
            return (Criteria) this;
        }

        public Criteria andParentIsNotNull() {
            addCriterion("parent is not null");
            return (Criteria) this;
        }

        public Criteria andParentEqualTo(String value) {
            addCriterion("parent =", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotEqualTo(String value) {
            addCriterion("parent <>", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThan(String value) {
            addCriterion("parent >", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThanOrEqualTo(String value) {
            addCriterion("parent >=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThan(String value) {
            addCriterion("parent <", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThanOrEqualTo(String value) {
            addCriterion("parent <=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLike(String value) {
            addCriterion("parent like", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotLike(String value) {
            addCriterion("parent not like", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentIn(List<String> values) {
            addCriterion("parent in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotIn(List<String> values) {
            addCriterion("parent not in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentBetween(String value1, String value2) {
            addCriterion("parent between", value1, value2, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotBetween(String value1, String value2) {
            addCriterion("parent not between", value1, value2, "parent");
            return (Criteria) this;
        }

        public Criteria andPnameIsNull() {
            addCriterion("pname is null");
            return (Criteria) this;
        }

        public Criteria andPnameIsNotNull() {
            addCriterion("pname is not null");
            return (Criteria) this;
        }

        public Criteria andPnameEqualTo(String value) {
            addCriterion("pname =", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotEqualTo(String value) {
            addCriterion("pname <>", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameGreaterThan(String value) {
            addCriterion("pname >", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameGreaterThanOrEqualTo(String value) {
            addCriterion("pname >=", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLessThan(String value) {
            addCriterion("pname <", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLessThanOrEqualTo(String value) {
            addCriterion("pname <=", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLike(String value) {
            addCriterion("pname like", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotLike(String value) {
            addCriterion("pname not like", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameIn(List<String> values) {
            addCriterion("pname in", values, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotIn(List<String> values) {
            addCriterion("pname not in", values, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameBetween(String value1, String value2) {
            addCriterion("pname between", value1, value2, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotBetween(String value1, String value2) {
            addCriterion("pname not between", value1, value2, "pname");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(String value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(String value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(String value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(String value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(String value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLike(String value) {
            addCriterion("birthday like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotLike(String value) {
            addCriterion("birthday not like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<String> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<String> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(String value1, String value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(String value1, String value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeIsNull() {
            addCriterion("registeretype is null");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeIsNotNull() {
            addCriterion("registeretype is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeEqualTo(String value) {
            addCriterion("registeretype =", value, "registeretype");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeNotEqualTo(String value) {
            addCriterion("registeretype <>", value, "registeretype");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeGreaterThan(String value) {
            addCriterion("registeretype >", value, "registeretype");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeGreaterThanOrEqualTo(String value) {
            addCriterion("registeretype >=", value, "registeretype");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeLessThan(String value) {
            addCriterion("registeretype <", value, "registeretype");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeLessThanOrEqualTo(String value) {
            addCriterion("registeretype <=", value, "registeretype");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeLike(String value) {
            addCriterion("registeretype like", value, "registeretype");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeNotLike(String value) {
            addCriterion("registeretype not like", value, "registeretype");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeIn(List<String> values) {
            addCriterion("registeretype in", values, "registeretype");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeNotIn(List<String> values) {
            addCriterion("registeretype not in", values, "registeretype");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeBetween(String value1, String value2) {
            addCriterion("registeretype between", value1, value2, "registeretype");
            return (Criteria) this;
        }

        public Criteria andRegisteretypeNotBetween(String value1, String value2) {
            addCriterion("registeretype not between", value1, value2, "registeretype");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceIsNull() {
            addCriterion("addrprovince is null");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceIsNotNull() {
            addCriterion("addrprovince is not null");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceEqualTo(String value) {
            addCriterion("addrprovince =", value, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceNotEqualTo(String value) {
            addCriterion("addrprovince <>", value, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceGreaterThan(String value) {
            addCriterion("addrprovince >", value, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceGreaterThanOrEqualTo(String value) {
            addCriterion("addrprovince >=", value, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceLessThan(String value) {
            addCriterion("addrprovince <", value, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceLessThanOrEqualTo(String value) {
            addCriterion("addrprovince <=", value, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceLike(String value) {
            addCriterion("addrprovince like", value, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceNotLike(String value) {
            addCriterion("addrprovince not like", value, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceIn(List<String> values) {
            addCriterion("addrprovince in", values, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceNotIn(List<String> values) {
            addCriterion("addrprovince not in", values, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceBetween(String value1, String value2) {
            addCriterion("addrprovince between", value1, value2, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrprovinceNotBetween(String value1, String value2) {
            addCriterion("addrprovince not between", value1, value2, "addrprovince");
            return (Criteria) this;
        }

        public Criteria andAddrcityIsNull() {
            addCriterion("addrcity is null");
            return (Criteria) this;
        }

        public Criteria andAddrcityIsNotNull() {
            addCriterion("addrcity is not null");
            return (Criteria) this;
        }

        public Criteria andAddrcityEqualTo(String value) {
            addCriterion("addrcity =", value, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcityNotEqualTo(String value) {
            addCriterion("addrcity <>", value, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcityGreaterThan(String value) {
            addCriterion("addrcity >", value, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcityGreaterThanOrEqualTo(String value) {
            addCriterion("addrcity >=", value, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcityLessThan(String value) {
            addCriterion("addrcity <", value, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcityLessThanOrEqualTo(String value) {
            addCriterion("addrcity <=", value, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcityLike(String value) {
            addCriterion("addrcity like", value, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcityNotLike(String value) {
            addCriterion("addrcity not like", value, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcityIn(List<String> values) {
            addCriterion("addrcity in", values, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcityNotIn(List<String> values) {
            addCriterion("addrcity not in", values, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcityBetween(String value1, String value2) {
            addCriterion("addrcity between", value1, value2, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcityNotBetween(String value1, String value2) {
            addCriterion("addrcity not between", value1, value2, "addrcity");
            return (Criteria) this;
        }

        public Criteria andAddrcountyIsNull() {
            addCriterion("addrcounty is null");
            return (Criteria) this;
        }

        public Criteria andAddrcountyIsNotNull() {
            addCriterion("addrcounty is not null");
            return (Criteria) this;
        }

        public Criteria andAddrcountyEqualTo(String value) {
            addCriterion("addrcounty =", value, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrcountyNotEqualTo(String value) {
            addCriterion("addrcounty <>", value, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrcountyGreaterThan(String value) {
            addCriterion("addrcounty >", value, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrcountyGreaterThanOrEqualTo(String value) {
            addCriterion("addrcounty >=", value, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrcountyLessThan(String value) {
            addCriterion("addrcounty <", value, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrcountyLessThanOrEqualTo(String value) {
            addCriterion("addrcounty <=", value, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrcountyLike(String value) {
            addCriterion("addrcounty like", value, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrcountyNotLike(String value) {
            addCriterion("addrcounty not like", value, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrcountyIn(List<String> values) {
            addCriterion("addrcounty in", values, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrcountyNotIn(List<String> values) {
            addCriterion("addrcounty not in", values, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrcountyBetween(String value1, String value2) {
            addCriterion("addrcounty between", value1, value2, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrcountyNotBetween(String value1, String value2) {
            addCriterion("addrcounty not between", value1, value2, "addrcounty");
            return (Criteria) this;
        }

        public Criteria andAddrtownIsNull() {
            addCriterion("addrtown is null");
            return (Criteria) this;
        }

        public Criteria andAddrtownIsNotNull() {
            addCriterion("addrtown is not null");
            return (Criteria) this;
        }

        public Criteria andAddrtownEqualTo(String value) {
            addCriterion("addrtown =", value, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrtownNotEqualTo(String value) {
            addCriterion("addrtown <>", value, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrtownGreaterThan(String value) {
            addCriterion("addrtown >", value, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrtownGreaterThanOrEqualTo(String value) {
            addCriterion("addrtown >=", value, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrtownLessThan(String value) {
            addCriterion("addrtown <", value, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrtownLessThanOrEqualTo(String value) {
            addCriterion("addrtown <=", value, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrtownLike(String value) {
            addCriterion("addrtown like", value, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrtownNotLike(String value) {
            addCriterion("addrtown not like", value, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrtownIn(List<String> values) {
            addCriterion("addrtown in", values, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrtownNotIn(List<String> values) {
            addCriterion("addrtown not in", values, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrtownBetween(String value1, String value2) {
            addCriterion("addrtown between", value1, value2, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrtownNotBetween(String value1, String value2) {
            addCriterion("addrtown not between", value1, value2, "addrtown");
            return (Criteria) this;
        }

        public Criteria andAddrvillageIsNull() {
            addCriterion("addrvillage is null");
            return (Criteria) this;
        }

        public Criteria andAddrvillageIsNotNull() {
            addCriterion("addrvillage is not null");
            return (Criteria) this;
        }

        public Criteria andAddrvillageEqualTo(String value) {
            addCriterion("addrvillage =", value, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrvillageNotEqualTo(String value) {
            addCriterion("addrvillage <>", value, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrvillageGreaterThan(String value) {
            addCriterion("addrvillage >", value, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrvillageGreaterThanOrEqualTo(String value) {
            addCriterion("addrvillage >=", value, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrvillageLessThan(String value) {
            addCriterion("addrvillage <", value, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrvillageLessThanOrEqualTo(String value) {
            addCriterion("addrvillage <=", value, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrvillageLike(String value) {
            addCriterion("addrvillage like", value, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrvillageNotLike(String value) {
            addCriterion("addrvillage not like", value, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrvillageIn(List<String> values) {
            addCriterion("addrvillage in", values, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrvillageNotIn(List<String> values) {
            addCriterion("addrvillage not in", values, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrvillageBetween(String value1, String value2) {
            addCriterion("addrvillage between", value1, value2, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrvillageNotBetween(String value1, String value2) {
            addCriterion("addrvillage not between", value1, value2, "addrvillage");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidIsNull() {
            addCriterion("addrhouseid is null");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidIsNotNull() {
            addCriterion("addrhouseid is not null");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidEqualTo(String value) {
            addCriterion("addrhouseid =", value, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidNotEqualTo(String value) {
            addCriterion("addrhouseid <>", value, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidGreaterThan(String value) {
            addCriterion("addrhouseid >", value, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidGreaterThanOrEqualTo(String value) {
            addCriterion("addrhouseid >=", value, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidLessThan(String value) {
            addCriterion("addrhouseid <", value, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidLessThanOrEqualTo(String value) {
            addCriterion("addrhouseid <=", value, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidLike(String value) {
            addCriterion("addrhouseid like", value, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidNotLike(String value) {
            addCriterion("addrhouseid not like", value, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidIn(List<String> values) {
            addCriterion("addrhouseid in", values, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidNotIn(List<String> values) {
            addCriterion("addrhouseid not in", values, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidBetween(String value1, String value2) {
            addCriterion("addrhouseid between", value1, value2, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andAddrhouseidNotBetween(String value1, String value2) {
            addCriterion("addrhouseid not between", value1, value2, "addrhouseid");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNull() {
            addCriterion("nationality is null");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNotNull() {
            addCriterion("nationality is not null");
            return (Criteria) this;
        }

        public Criteria andNationalityEqualTo(String value) {
            addCriterion("nationality =", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotEqualTo(String value) {
            addCriterion("nationality <>", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThan(String value) {
            addCriterion("nationality >", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThanOrEqualTo(String value) {
            addCriterion("nationality >=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThan(String value) {
            addCriterion("nationality <", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThanOrEqualTo(String value) {
            addCriterion("nationality <=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLike(String value) {
            addCriterion("nationality like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotLike(String value) {
            addCriterion("nationality not like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityIn(List<String> values) {
            addCriterion("nationality in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotIn(List<String> values) {
            addCriterion("nationality not in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityBetween(String value1, String value2) {
            addCriterion("nationality between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotBetween(String value1, String value2) {
            addCriterion("nationality not between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusIsNull() {
            addCriterion("marriedstatus is null");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusIsNotNull() {
            addCriterion("marriedstatus is not null");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusEqualTo(String value) {
            addCriterion("marriedstatus =", value, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusNotEqualTo(String value) {
            addCriterion("marriedstatus <>", value, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusGreaterThan(String value) {
            addCriterion("marriedstatus >", value, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusGreaterThanOrEqualTo(String value) {
            addCriterion("marriedstatus >=", value, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusLessThan(String value) {
            addCriterion("marriedstatus <", value, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusLessThanOrEqualTo(String value) {
            addCriterion("marriedstatus <=", value, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusLike(String value) {
            addCriterion("marriedstatus like", value, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusNotLike(String value) {
            addCriterion("marriedstatus not like", value, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusIn(List<String> values) {
            addCriterion("marriedstatus in", values, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusNotIn(List<String> values) {
            addCriterion("marriedstatus not in", values, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusBetween(String value1, String value2) {
            addCriterion("marriedstatus between", value1, value2, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andMarriedstatusNotBetween(String value1, String value2) {
            addCriterion("marriedstatus not between", value1, value2, "marriedstatus");
            return (Criteria) this;
        }

        public Criteria andNationIsNull() {
            addCriterion("nation is null");
            return (Criteria) this;
        }

        public Criteria andNationIsNotNull() {
            addCriterion("nation is not null");
            return (Criteria) this;
        }

        public Criteria andNationEqualTo(String value) {
            addCriterion("nation =", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotEqualTo(String value) {
            addCriterion("nation <>", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThan(String value) {
            addCriterion("nation >", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThanOrEqualTo(String value) {
            addCriterion("nation >=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThan(String value) {
            addCriterion("nation <", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThanOrEqualTo(String value) {
            addCriterion("nation <=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLike(String value) {
            addCriterion("nation like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotLike(String value) {
            addCriterion("nation not like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationIn(List<String> values) {
            addCriterion("nation in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotIn(List<String> values) {
            addCriterion("nation not in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationBetween(String value1, String value2) {
            addCriterion("nation between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotBetween(String value1, String value2) {
            addCriterion("nation not between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andBooldtypeIsNull() {
            addCriterion("booldType is null");
            return (Criteria) this;
        }

        public Criteria andBooldtypeIsNotNull() {
            addCriterion("booldType is not null");
            return (Criteria) this;
        }

        public Criteria andBooldtypeEqualTo(String value) {
            addCriterion("booldType =", value, "booldtype");
            return (Criteria) this;
        }

        public Criteria andBooldtypeNotEqualTo(String value) {
            addCriterion("booldType <>", value, "booldtype");
            return (Criteria) this;
        }

        public Criteria andBooldtypeGreaterThan(String value) {
            addCriterion("booldType >", value, "booldtype");
            return (Criteria) this;
        }

        public Criteria andBooldtypeGreaterThanOrEqualTo(String value) {
            addCriterion("booldType >=", value, "booldtype");
            return (Criteria) this;
        }

        public Criteria andBooldtypeLessThan(String value) {
            addCriterion("booldType <", value, "booldtype");
            return (Criteria) this;
        }

        public Criteria andBooldtypeLessThanOrEqualTo(String value) {
            addCriterion("booldType <=", value, "booldtype");
            return (Criteria) this;
        }

        public Criteria andBooldtypeLike(String value) {
            addCriterion("booldType like", value, "booldtype");
            return (Criteria) this;
        }

        public Criteria andBooldtypeNotLike(String value) {
            addCriterion("booldType not like", value, "booldtype");
            return (Criteria) this;
        }

        public Criteria andBooldtypeIn(List<String> values) {
            addCriterion("booldType in", values, "booldtype");
            return (Criteria) this;
        }

        public Criteria andBooldtypeNotIn(List<String> values) {
            addCriterion("booldType not in", values, "booldtype");
            return (Criteria) this;
        }

        public Criteria andBooldtypeBetween(String value1, String value2) {
            addCriterion("booldType between", value1, value2, "booldtype");
            return (Criteria) this;
        }

        public Criteria andBooldtypeNotBetween(String value1, String value2) {
            addCriterion("booldType not between", value1, value2, "booldtype");
            return (Criteria) this;
        }

        public Criteria andRhIsNull() {
            addCriterion("rh is null");
            return (Criteria) this;
        }

        public Criteria andRhIsNotNull() {
            addCriterion("rh is not null");
            return (Criteria) this;
        }

        public Criteria andRhEqualTo(String value) {
            addCriterion("rh =", value, "rh");
            return (Criteria) this;
        }

        public Criteria andRhNotEqualTo(String value) {
            addCriterion("rh <>", value, "rh");
            return (Criteria) this;
        }

        public Criteria andRhGreaterThan(String value) {
            addCriterion("rh >", value, "rh");
            return (Criteria) this;
        }

        public Criteria andRhGreaterThanOrEqualTo(String value) {
            addCriterion("rh >=", value, "rh");
            return (Criteria) this;
        }

        public Criteria andRhLessThan(String value) {
            addCriterion("rh <", value, "rh");
            return (Criteria) this;
        }

        public Criteria andRhLessThanOrEqualTo(String value) {
            addCriterion("rh <=", value, "rh");
            return (Criteria) this;
        }

        public Criteria andRhLike(String value) {
            addCriterion("rh like", value, "rh");
            return (Criteria) this;
        }

        public Criteria andRhNotLike(String value) {
            addCriterion("rh not like", value, "rh");
            return (Criteria) this;
        }

        public Criteria andRhIn(List<String> values) {
            addCriterion("rh in", values, "rh");
            return (Criteria) this;
        }

        public Criteria andRhNotIn(List<String> values) {
            addCriterion("rh not in", values, "rh");
            return (Criteria) this;
        }

        public Criteria andRhBetween(String value1, String value2) {
            addCriterion("rh between", value1, value2, "rh");
            return (Criteria) this;
        }

        public Criteria andRhNotBetween(String value1, String value2) {
            addCriterion("rh not between", value1, value2, "rh");
            return (Criteria) this;
        }

        public Criteria andWorkdateIsNull() {
            addCriterion("workdate is null");
            return (Criteria) this;
        }

        public Criteria andWorkdateIsNotNull() {
            addCriterion("workdate is not null");
            return (Criteria) this;
        }

        public Criteria andWorkdateEqualTo(String value) {
            addCriterion("workdate =", value, "workdate");
            return (Criteria) this;
        }

        public Criteria andWorkdateNotEqualTo(String value) {
            addCriterion("workdate <>", value, "workdate");
            return (Criteria) this;
        }

        public Criteria andWorkdateGreaterThan(String value) {
            addCriterion("workdate >", value, "workdate");
            return (Criteria) this;
        }

        public Criteria andWorkdateGreaterThanOrEqualTo(String value) {
            addCriterion("workdate >=", value, "workdate");
            return (Criteria) this;
        }

        public Criteria andWorkdateLessThan(String value) {
            addCriterion("workdate <", value, "workdate");
            return (Criteria) this;
        }

        public Criteria andWorkdateLessThanOrEqualTo(String value) {
            addCriterion("workdate <=", value, "workdate");
            return (Criteria) this;
        }

        public Criteria andWorkdateLike(String value) {
            addCriterion("workdate like", value, "workdate");
            return (Criteria) this;
        }

        public Criteria andWorkdateNotLike(String value) {
            addCriterion("workdate not like", value, "workdate");
            return (Criteria) this;
        }

        public Criteria andWorkdateIn(List<String> values) {
            addCriterion("workdate in", values, "workdate");
            return (Criteria) this;
        }

        public Criteria andWorkdateNotIn(List<String> values) {
            addCriterion("workdate not in", values, "workdate");
            return (Criteria) this;
        }

        public Criteria andWorkdateBetween(String value1, String value2) {
            addCriterion("workdate between", value1, value2, "workdate");
            return (Criteria) this;
        }

        public Criteria andWorkdateNotBetween(String value1, String value2) {
            addCriterion("workdate not between", value1, value2, "workdate");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeIsNull() {
            addCriterion("jobtypecode is null");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeIsNotNull() {
            addCriterion("jobtypecode is not null");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeEqualTo(String value) {
            addCriterion("jobtypecode =", value, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeNotEqualTo(String value) {
            addCriterion("jobtypecode <>", value, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeGreaterThan(String value) {
            addCriterion("jobtypecode >", value, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeGreaterThanOrEqualTo(String value) {
            addCriterion("jobtypecode >=", value, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeLessThan(String value) {
            addCriterion("jobtypecode <", value, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeLessThanOrEqualTo(String value) {
            addCriterion("jobtypecode <=", value, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeLike(String value) {
            addCriterion("jobtypecode like", value, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeNotLike(String value) {
            addCriterion("jobtypecode not like", value, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeIn(List<String> values) {
            addCriterion("jobtypecode in", values, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeNotIn(List<String> values) {
            addCriterion("jobtypecode not in", values, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeBetween(String value1, String value2) {
            addCriterion("jobtypecode between", value1, value2, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andJobtypecodeNotBetween(String value1, String value2) {
            addCriterion("jobtypecode not between", value1, value2, "jobtypecode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeIsNull() {
            addCriterion("educationcode is null");
            return (Criteria) this;
        }

        public Criteria andEducationcodeIsNotNull() {
            addCriterion("educationcode is not null");
            return (Criteria) this;
        }

        public Criteria andEducationcodeEqualTo(String value) {
            addCriterion("educationcode =", value, "educationcode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeNotEqualTo(String value) {
            addCriterion("educationcode <>", value, "educationcode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeGreaterThan(String value) {
            addCriterion("educationcode >", value, "educationcode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeGreaterThanOrEqualTo(String value) {
            addCriterion("educationcode >=", value, "educationcode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeLessThan(String value) {
            addCriterion("educationcode <", value, "educationcode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeLessThanOrEqualTo(String value) {
            addCriterion("educationcode <=", value, "educationcode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeLike(String value) {
            addCriterion("educationcode like", value, "educationcode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeNotLike(String value) {
            addCriterion("educationcode not like", value, "educationcode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeIn(List<String> values) {
            addCriterion("educationcode in", values, "educationcode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeNotIn(List<String> values) {
            addCriterion("educationcode not in", values, "educationcode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeBetween(String value1, String value2) {
            addCriterion("educationcode between", value1, value2, "educationcode");
            return (Criteria) this;
        }

        public Criteria andEducationcodeNotBetween(String value1, String value2) {
            addCriterion("educationcode not between", value1, value2, "educationcode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeIsNull() {
            addCriterion("degreecode is null");
            return (Criteria) this;
        }

        public Criteria andDegreecodeIsNotNull() {
            addCriterion("degreecode is not null");
            return (Criteria) this;
        }

        public Criteria andDegreecodeEqualTo(String value) {
            addCriterion("degreecode =", value, "degreecode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeNotEqualTo(String value) {
            addCriterion("degreecode <>", value, "degreecode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeGreaterThan(String value) {
            addCriterion("degreecode >", value, "degreecode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeGreaterThanOrEqualTo(String value) {
            addCriterion("degreecode >=", value, "degreecode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeLessThan(String value) {
            addCriterion("degreecode <", value, "degreecode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeLessThanOrEqualTo(String value) {
            addCriterion("degreecode <=", value, "degreecode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeLike(String value) {
            addCriterion("degreecode like", value, "degreecode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeNotLike(String value) {
            addCriterion("degreecode not like", value, "degreecode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeIn(List<String> values) {
            addCriterion("degreecode in", values, "degreecode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeNotIn(List<String> values) {
            addCriterion("degreecode not in", values, "degreecode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeBetween(String value1, String value2) {
            addCriterion("degreecode between", value1, value2, "degreecode");
            return (Criteria) this;
        }

        public Criteria andDegreecodeNotBetween(String value1, String value2) {
            addCriterion("degreecode not between", value1, value2, "degreecode");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("_version_ is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("_version_ is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("_version_ =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("_version_ <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("_version_ >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("_version_ >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("_version_ <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("_version_ <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("_version_ in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("_version_ not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("_version_ between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("_version_ not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNull() {
            addCriterion("isdel is null");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNotNull() {
            addCriterion("isdel is not null");
            return (Criteria) this;
        }

        public Criteria andIsdelEqualTo(String value) {
            addCriterion("isdel =", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotEqualTo(String value) {
            addCriterion("isdel <>", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThan(String value) {
            addCriterion("isdel >", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThanOrEqualTo(String value) {
            addCriterion("isdel >=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThan(String value) {
            addCriterion("isdel <", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThanOrEqualTo(String value) {
            addCriterion("isdel <=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLike(String value) {
            addCriterion("isdel like", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotLike(String value) {
            addCriterion("isdel not like", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelIn(List<String> values) {
            addCriterion("isdel in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotIn(List<String> values) {
            addCriterion("isdel not in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelBetween(String value1, String value2) {
            addCriterion("isdel between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotBetween(String value1, String value2) {
            addCriterion("isdel not between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("PID is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("PID is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("PID =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("PID <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("PID >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("PID >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("PID <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("PID <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("PID like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("PID not like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("PID in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("PID not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("PID between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("PID not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterionForJDBCDate("createdate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("createdate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterionForJDBCDate("createdate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("createdate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterionForJDBCDate("createdate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("createdate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterionForJDBCDate("createdate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("createdate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("createdate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("createdate not between", value1, value2, "createdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table empi_person
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 08 16:15:11 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}