package com.livechain.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PersonInDataExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public PersonInDataExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andLidIsNull() {
			addCriterion("lid is null");
			return (Criteria) this;
		}

		public Criteria andLidIsNotNull() {
			addCriterion("lid is not null");
			return (Criteria) this;
		}

		public Criteria andLidEqualTo(Integer value) {
			addCriterion("lid =", value, "lid");
			return (Criteria) this;
		}

		public Criteria andLidNotEqualTo(Integer value) {
			addCriterion("lid <>", value, "lid");
			return (Criteria) this;
		}

		public Criteria andLidGreaterThan(Integer value) {
			addCriterion("lid >", value, "lid");
			return (Criteria) this;
		}

		public Criteria andLidGreaterThanOrEqualTo(Integer value) {
			addCriterion("lid >=", value, "lid");
			return (Criteria) this;
		}

		public Criteria andLidLessThan(Integer value) {
			addCriterion("lid <", value, "lid");
			return (Criteria) this;
		}

		public Criteria andLidLessThanOrEqualTo(Integer value) {
			addCriterion("lid <=", value, "lid");
			return (Criteria) this;
		}

		public Criteria andLidIn(List<Integer> values) {
			addCriterion("lid in", values, "lid");
			return (Criteria) this;
		}

		public Criteria andLidNotIn(List<Integer> values) {
			addCriterion("lid not in", values, "lid");
			return (Criteria) this;
		}

		public Criteria andLidBetween(Integer value1, Integer value2) {
			addCriterion("lid between", value1, value2, "lid");
			return (Criteria) this;
		}

		public Criteria andLidNotBetween(Integer value1, Integer value2) {
			addCriterion("lid not between", value1, value2, "lid");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createdate is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createdate is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterionForJDBCDate("createdate =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterionForJDBCDate("createdate <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterionForJDBCDate("createdate >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("createdate >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterionForJDBCDate("createdate <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("createdate <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterionForJDBCDate("createdate in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterionForJDBCDate("createdate not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("createdate between", value1, value2,
					"createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("createdate not between", value1, value2,
					"createdate");
			return (Criteria) this;
		}

		public Criteria andPidIsNull() {
			addCriterion("pid is null");
			return (Criteria) this;
		}

		public Criteria andPidIsNotNull() {
			addCriterion("pid is not null");
			return (Criteria) this;
		}

		public Criteria andPidEqualTo(String value) {
			addCriterion("pid =", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotEqualTo(String value) {
			addCriterion("pid <>", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidGreaterThan(String value) {
			addCriterion("pid >", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidGreaterThanOrEqualTo(String value) {
			addCriterion("pid >=", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLessThan(String value) {
			addCriterion("pid <", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLessThanOrEqualTo(String value) {
			addCriterion("pid <=", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLike(String value) {
			addCriterion("pid like", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotLike(String value) {
			addCriterion("pid not like", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidIn(List<String> values) {
			addCriterion("pid in", values, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotIn(List<String> values) {
			addCriterion("pid not in", values, "pid");
			return (Criteria) this;
		}

		public Criteria andPidBetween(String value1, String value2) {
			addCriterion("pid between", value1, value2, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotBetween(String value1, String value2) {
			addCriterion("pid not between", value1, value2, "pid");
			return (Criteria) this;
		}

		public Criteria andActionIsNull() {
			addCriterion("action is null");
			return (Criteria) this;
		}

		public Criteria andActionIsNotNull() {
			addCriterion("action is not null");
			return (Criteria) this;
		}

		public Criteria andActionEqualTo(String value) {
			addCriterion("action =", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotEqualTo(String value) {
			addCriterion("action <>", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThan(String value) {
			addCriterion("action >", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThanOrEqualTo(String value) {
			addCriterion("action >=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThan(String value) {
			addCriterion("action <", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThanOrEqualTo(String value) {
			addCriterion("action <=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLike(String value) {
			addCriterion("action like", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotLike(String value) {
			addCriterion("action not like", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionIn(List<String> values) {
			addCriterion("action in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotIn(List<String> values) {
			addCriterion("action not in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionBetween(String value1, String value2) {
			addCriterion("action between", value1, value2, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotBetween(String value1, String value2) {
			addCriterion("action not between", value1, value2, "action");
			return (Criteria) this;
		}

		public Criteria andClientIsNull() {
			addCriterion("client is null");
			return (Criteria) this;
		}

		public Criteria andClientIsNotNull() {
			addCriterion("client is not null");
			return (Criteria) this;
		}

		public Criteria andClientEqualTo(String value) {
			addCriterion("client =", value, "client");
			return (Criteria) this;
		}

		public Criteria andClientNotEqualTo(String value) {
			addCriterion("client <>", value, "client");
			return (Criteria) this;
		}

		public Criteria andClientGreaterThan(String value) {
			addCriterion("client >", value, "client");
			return (Criteria) this;
		}

		public Criteria andClientGreaterThanOrEqualTo(String value) {
			addCriterion("client >=", value, "client");
			return (Criteria) this;
		}

		public Criteria andClientLessThan(String value) {
			addCriterion("client <", value, "client");
			return (Criteria) this;
		}

		public Criteria andClientLessThanOrEqualTo(String value) {
			addCriterion("client <=", value, "client");
			return (Criteria) this;
		}

		public Criteria andClientLike(String value) {
			addCriterion("client like", value, "client");
			return (Criteria) this;
		}

		public Criteria andClientNotLike(String value) {
			addCriterion("client not like", value, "client");
			return (Criteria) this;
		}

		public Criteria andClientIn(List<String> values) {
			addCriterion("client in", values, "client");
			return (Criteria) this;
		}

		public Criteria andClientNotIn(List<String> values) {
			addCriterion("client not in", values, "client");
			return (Criteria) this;
		}

		public Criteria andClientBetween(String value1, String value2) {
			addCriterion("client between", value1, value2, "client");
			return (Criteria) this;
		}

		public Criteria andClientNotBetween(String value1, String value2) {
			addCriterion("client not between", value1, value2, "client");
			return (Criteria) this;
		}

		public Criteria andObjidIsNull() {
			addCriterion("objid is null");
			return (Criteria) this;
		}

		public Criteria andObjidIsNotNull() {
			addCriterion("objid is not null");
			return (Criteria) this;
		}

		public Criteria andObjidEqualTo(String value) {
			addCriterion("objid =", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidNotEqualTo(String value) {
			addCriterion("objid <>", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidGreaterThan(String value) {
			addCriterion("objid >", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidGreaterThanOrEqualTo(String value) {
			addCriterion("objid >=", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidLessThan(String value) {
			addCriterion("objid <", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidLessThanOrEqualTo(String value) {
			addCriterion("objid <=", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidLike(String value) {
			addCriterion("objid like", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidNotLike(String value) {
			addCriterion("objid not like", value, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidIn(List<String> values) {
			addCriterion("objid in", values, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidNotIn(List<String> values) {
			addCriterion("objid not in", values, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidBetween(String value1, String value2) {
			addCriterion("objid between", value1, value2, "objid");
			return (Criteria) this;
		}

		public Criteria andObjidNotBetween(String value1, String value2) {
			addCriterion("objid not between", value1, value2, "objid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table personindata
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 13 15:18:09 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}