package com.livechain.mybatis.model;

import java.util.Date;
import java.util.List;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.parent
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
	  private String addr;//地址
	  private String idcard;//身份证
	  public String getAddr() {
		return addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	public String getIdcard() {
		return idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	private List<Credentials> credentials;//证件
	    private List<Phones> phones;//电话
	    private List<OrgCodes> orgcodes;//机构代码
		public List<Credentials> getCredentials() {
			return credentials;
		}

		public void setCredentials(List<Credentials> credentials) {
			this.credentials = credentials;
		}

		public List<Phones> getPhones() {
			return phones;
		}

		public void setPhones(List<Phones> phones) {
			this.phones = phones;
		}

		public List<OrgCodes> getOrgcodes() {
			return orgcodes;
		}

		public void setOrgcodes(List<OrgCodes> orgcodes) {
			this.orgcodes = orgcodes;
		}
   private String similarity;

	public String getSimilarity() {
	return similarity;
}

public void setSimilarity(String similarity) {
	this.similarity = similarity;
}

	private String parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.pname
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.gender
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.birthday
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.email
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.nickname
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.registeretype
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String registeretype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.addrprovince
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String addrprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.addrcity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String addrcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.addrcounty
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String addrcounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.addrtown
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String addrtown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.addrvillage
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String addrvillage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.addrhouseid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String addrhouseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.nationality
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.marriedstatus
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String marriedstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.nation
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.age
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.booldType
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String booldtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.rh
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String rh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.workdate
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String workdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.jobtypecode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String jobtypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.educationcode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String educationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.degreecode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String degreecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person._version_
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.isdel
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String isdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.status
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.createdate
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private Date createdate;

   

	

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_person.person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String person;
    
 


	

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.parent
     *
     * @return the value of empi_person.parent
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.parent
     *
     * @param parent the value for empi_person.parent
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setParent(String parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.pname
     *
     * @return the value of empi_person.pname
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.pname
     *
     * @param pname the value for empi_person.pname
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.gender
     *
     * @return the value of empi_person.gender
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.gender
     *
     * @param gender the value for empi_person.gender
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.birthday
     *
     * @return the value of empi_person.birthday
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.birthday
     *
     * @param birthday the value for empi_person.birthday
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.email
     *
     * @return the value of empi_person.email
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.email
     *
     * @param email the value for empi_person.email
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.nickname
     *
     * @return the value of empi_person.nickname
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.nickname
     *
     * @param nickname the value for empi_person.nickname
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.registeretype
     *
     * @return the value of empi_person.registeretype
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getRegisteretype() {
        return registeretype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.registeretype
     *
     * @param registeretype the value for empi_person.registeretype
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setRegisteretype(String registeretype) {
        this.registeretype = registeretype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.addrprovince
     *
     * @return the value of empi_person.addrprovince
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getAddrprovince() {
        return addrprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.addrprovince
     *
     * @param addrprovince the value for empi_person.addrprovince
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setAddrprovince(String addrprovince) {
        this.addrprovince = addrprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.addrcity
     *
     * @return the value of empi_person.addrcity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getAddrcity() {
        return addrcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.addrcity
     *
     * @param addrcity the value for empi_person.addrcity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setAddrcity(String addrcity) {
        this.addrcity = addrcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.addrcounty
     *
     * @return the value of empi_person.addrcounty
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getAddrcounty() {
        return addrcounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.addrcounty
     *
     * @param addrcounty the value for empi_person.addrcounty
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setAddrcounty(String addrcounty) {
        this.addrcounty = addrcounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.addrtown
     *
     * @return the value of empi_person.addrtown
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getAddrtown() {
        return addrtown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.addrtown
     *
     * @param addrtown the value for empi_person.addrtown
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setAddrtown(String addrtown) {
        this.addrtown = addrtown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.addrvillage
     *
     * @return the value of empi_person.addrvillage
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getAddrvillage() {
        return addrvillage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.addrvillage
     *
     * @param addrvillage the value for empi_person.addrvillage
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setAddrvillage(String addrvillage) {
        this.addrvillage = addrvillage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.addrhouseid
     *
     * @return the value of empi_person.addrhouseid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getAddrhouseid() {
        return addrhouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.addrhouseid
     *
     * @param addrhouseid the value for empi_person.addrhouseid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setAddrhouseid(String addrhouseid) {
        this.addrhouseid = addrhouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.nationality
     *
     * @return the value of empi_person.nationality
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.nationality
     *
     * @param nationality the value for empi_person.nationality
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.marriedstatus
     *
     * @return the value of empi_person.marriedstatus
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getMarriedstatus() {
        return marriedstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.marriedstatus
     *
     * @param marriedstatus the value for empi_person.marriedstatus
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setMarriedstatus(String marriedstatus) {
        this.marriedstatus = marriedstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.nation
     *
     * @return the value of empi_person.nation
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.nation
     *
     * @param nation the value for empi_person.nation
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.age
     *
     * @return the value of empi_person.age
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.age
     *
     * @param age the value for empi_person.age
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.booldType
     *
     * @return the value of empi_person.booldType
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getBooldtype() {
        return booldtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.booldType
     *
     * @param booldtype the value for empi_person.booldType
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setBooldtype(String booldtype) {
        this.booldtype = booldtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.rh
     *
     * @return the value of empi_person.rh
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getRh() {
        return rh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.rh
     *
     * @param rh the value for empi_person.rh
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setRh(String rh) {
        this.rh = rh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.workdate
     *
     * @return the value of empi_person.workdate
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getWorkdate() {
        return workdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.workdate
     *
     * @param workdate the value for empi_person.workdate
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setWorkdate(String workdate) {
        this.workdate = workdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.jobtypecode
     *
     * @return the value of empi_person.jobtypecode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getJobtypecode() {
        return jobtypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.jobtypecode
     *
     * @param jobtypecode the value for empi_person.jobtypecode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setJobtypecode(String jobtypecode) {
        this.jobtypecode = jobtypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.educationcode
     *
     * @return the value of empi_person.educationcode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getEducationcode() {
        return educationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.educationcode
     *
     * @param educationcode the value for empi_person.educationcode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setEducationcode(String educationcode) {
        this.educationcode = educationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.degreecode
     *
     * @return the value of empi_person.degreecode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getDegreecode() {
        return degreecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.degreecode
     *
     * @param degreecode the value for empi_person.degreecode
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setDegreecode(String degreecode) {
        this.degreecode = degreecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person._version_
     *
     * @return the value of empi_person._version_
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person._version_
     *
     * @param version the value for empi_person._version_
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.isdel
     *
     * @return the value of empi_person.isdel
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.isdel
     *
     * @param isdel the value for empi_person.isdel
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setIsdel(String isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.status
     *
     * @return the value of empi_person.status
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.status
     *
     * @param status the value for empi_person.status
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.PID
     *
     * @return the value of empi_person.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.PID
     *
     * @param pid the value for empi_person.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.createdate
     *
     * @return the value of empi_person.createdate
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.createdate
     *
     * @param createdate the value for empi_person.createdate
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_person.person
     *
     * @return the value of empi_person.person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_person.person
     *
     * @param person the value for empi_person.person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setPerson(String person) {
        this.person = person;
    }
}