package com.livechain.mybatis.model;

import java.util.Date;

public class PersonInData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personindata.lid
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	private Integer lid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personindata.createdate
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personindata.pid
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	private String pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personindata.action
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	private String action;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personindata.client
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	private String client;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column personindata.objid
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	private String objid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personindata.lid
	 * @return  the value of personindata.lid
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public Integer getLid() {
		return lid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personindata.lid
	 * @param lid  the value for personindata.lid
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void setLid(Integer lid) {
		this.lid = lid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personindata.createdate
	 * @return  the value of personindata.createdate
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personindata.createdate
	 * @param createdate  the value for personindata.createdate
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personindata.pid
	 * @return  the value of personindata.pid
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personindata.pid
	 * @param pid  the value for personindata.pid
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personindata.action
	 * @return  the value of personindata.action
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public String getAction() {
		return action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personindata.action
	 * @param action  the value for personindata.action
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personindata.client
	 * @return  the value of personindata.client
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public String getClient() {
		return client;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personindata.client
	 * @param client  the value for personindata.client
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void setClient(String client) {
		this.client = client;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column personindata.objid
	 * @return  the value of personindata.objid
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public String getObjid() {
		return objid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column personindata.objid
	 * @param objid  the value for personindata.objid
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	public void setObjid(String objid) {
		this.objid = objid;
	}
}