package com.livechain.mybatis.model;

import java.util.Date;

public class Phones {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_phones.phid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private Integer phid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_phones.type
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_phones.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_phones.num
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_phones.regtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_phones.status
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_phones.phid
     *
     * @return the value of empi_phones.phid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public Integer getPhid() {
        return phid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_phones.phid
     *
     * @param phid the value for empi_phones.phid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setPhid(Integer phid) {
        this.phid = phid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_phones.type
     *
     * @return the value of empi_phones.type
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_phones.type
     *
     * @param type the value for empi_phones.type
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_phones.PID
     *
     * @return the value of empi_phones.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_phones.PID
     *
     * @param pid the value for empi_phones.PID
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_phones.num
     *
     * @return the value of empi_phones.num
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_phones.num
     *
     * @param num the value for empi_phones.num
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_phones.regtime
     *
     * @return the value of empi_phones.regtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_phones.regtime
     *
     * @param regtime the value for empi_phones.regtime
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_phones.status
     *
     * @return the value of empi_phones.status
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_phones.status
     *
     * @param status the value for empi_phones.status
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setStatus(String status) {
        this.status = status;
    }
}