package com.livechain.mybatis.model;

public class SimilarityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_similarity.pid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empi_similarity.similarity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    private String similarity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_similarity.pid
     *
     * @return the value of empi_similarity.pid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_similarity.pid
     *
     * @param pid the value for empi_similarity.pid
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empi_similarity.similarity
     *
     * @return the value of empi_similarity.similarity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public String getSimilarity() {
        return similarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empi_similarity.similarity
     *
     * @param similarity the value for empi_similarity.similarity
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    public void setSimilarity(String similarity) {
        this.similarity = similarity;
    }
}