package com.livechain.mybatis.dao;



import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.livechain.mybatis.model.Credentials;
import com.livechain.mybatis.model.CredentialsExample;

@MyBatisRepository
public interface CredentialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_credentials
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int countByExample(CredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_credentials
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int deleteByExample(CredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_credentials
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int deleteByPrimaryKey(Integer crdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_credentials
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int insert(Credentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_credentials
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int insertSelective(Credentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_credentials
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    List<Credentials> selectByExample(CredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_credentials
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    Credentials selectByPrimaryKey(Integer crdid);
    /**

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_credentials
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByExampleSelective(@Param("record") Credentials record, @Param("example") CredentialsExample example);
    /**
     * liuwei
     */
    int updateByExampleSelectiveperspn(@Param("record") Credentials record, @Param("example") CredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_credentials
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByExample(@Param("record") Credentials record, @Param("example") CredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_credentials
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByPrimaryKeySelective(Credentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_credentials
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByPrimaryKey(Credentials record);
}