package com.livechain.mybatis.dao;

import com.livechain.mybatis.model.PersonInData;
import com.livechain.mybatis.model.PersonInDataExample;
import com.livechain.mybatis.model.PersonInDataWithBLOBs;

import java.util.List;

import org.apache.ibatis.annotations.Param;
@MyBatisRepository
public interface PersonInDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	int countByExample(PersonInDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	int deleteByExample(PersonInDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	int deleteByPrimaryKey(Integer lid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	int insert(PersonInDataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	int insertSelective(PersonInDataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	List<PersonInDataWithBLOBs> selectByExampleWithBLOBs(
			PersonInDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	List<PersonInData> selectByExample(PersonInDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	PersonInDataWithBLOBs selectByPrimaryKey(Integer lid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PersonInDataWithBLOBs record,
			@Param("example") PersonInDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") PersonInDataWithBLOBs record,
			@Param("example") PersonInDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	int updateByExample(@Param("record") PersonInData record,
			@Param("example") PersonInDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	int updateByPrimaryKeySelective(PersonInDataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(PersonInDataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personindata
	 * @mbggenerated  Tue Aug 13 16:59:02 CST 2013
	 */
	int updateByPrimaryKey(PersonInData record);
}