package com.livechain.mybatis.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.livechain.mybatis.model.Person;
import com.livechain.mybatis.model.PersonExample;
import com.livechain.pid.rest.model.GetlockpersonsIn;
import com.livechain.pid.rest.model.GetpersonsIn;
import com.livechain.pid.rest.model.GetsimilaritbypidIn;
import com.livechain.pid.rest.model.GetsimilaritiesIn;

@MyBatisRepository
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    List<Person> selectByExampleWithBLOBs(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    List<Person> selectByExample(PersonExample example);

    
    List<Person> getSimilarity (@Param("record") RowBounds record,@Param("getsimilaritiesin") GetsimilaritiesIn gi);

    List<Person> selectByExamplePage(@Param("rowBounds") RowBounds rowBounds,@Param("example") PersonExample example);
    /**
     * add by : wangyy time :2013-08-17 select person by credentials .
     */
    
    List<Person> getPersons (@Param("record") RowBounds record,@Param("getpersonsin") GetpersonsIn in);
    List<Person> getsimilaritbypid (GetsimilaritbypidIn gin);
    
    /**
     * add by : wangyy time :2013-08-17 select person by credentials .
     */
    int getPersonscount (GetpersonsIn in);
    int getSimilaritycount (GetsimilaritiesIn gi);
   
    /**
     * add by : wangyy time :2013-09-02 select person by credentials .
     */
    List<Person> getPersonslock (@Param("record") RowBounds record,@Param("getlockpersonsin") GetlockpersonsIn in);
    int getPersonslockcount (GetlockpersonsIn in);
    /**
     * This method was generated by MyBatis Generatsor.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    Person selectByPrimaryKey(String pid);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_person
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByPrimaryKey(Person record);
}