package com.livechain.mybatis.dao;


import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.livechain.mybatis.model.Phones;
import com.livechain.mybatis.model.PhonesExample;
@MyBatisRepository
public interface PhonesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_phones
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int countByExample(PhonesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_phones
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int deleteByExample(PhonesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_phones
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int deleteByPrimaryKey(Integer phid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_phones
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int insert(Phones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_phones
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int insertSelective(Phones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_phones
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    List<Phones> selectByExample(PhonesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_phones
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    Phones selectByPrimaryKey(Integer phid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_phones
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByExampleSelective(@Param("record") Phones record, @Param("example") PhonesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_phones
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByExample(@Param("record") Phones record, @Param("example") PhonesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_phones
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByPrimaryKeySelective(Phones record);
    
    /**
     * liuwei
     */
    int updateByPrimaryKeySelectivephones(Phones record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empi_phones
     *
     * @mbggenerated Thu Aug 08 16:15:11 CST 2013
     */
    int updateByPrimaryKey(Phones record);
}